//HOMEPAGE actions
export const HOMEPAGE_TEXT_CHANGED = "HOMEPAGE_TEXT_CHANGED";
export const HOMEPAGE_RESPONSE_APPEARED = "HOMEPAGE_RESPONSE_APPEARED";
export const HOMEPAGE_REQUEST_LOADING = "HOMEPAGE_REQUEST_LOADING";
